myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app import views, forms
import django.contrib.auth.views
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from app.views import register_seller
from quotation.views import create_quotation,create_quotationID,sview_Quotation,slquotation
from PurchaseOrder.views import create_POID, create_PurchaseOrder
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^contact$', views.contact, name='contact'),
    re_path(r'^about$', views.about, name='about'),
    re_path(r'^login/$',
        LoginView.as_view(template_name = 'app/login.html'),
        name='login'),
    re_path(r'^logout$',
        LogoutView.as_view(template_name = 'app/index.html'),
        name='logout'),
    re_path(r'^menu$', views.menu, name='menu'),
    path('register/', register_seller, name='register'),
    path('createquotation/',create_quotationID, name='create_quotationID'),
    path('createquotation/<int:pk>/',create_quotation, name='create_quotation'),
    path('sview_Quotation/', sview_Quotation , name = 'sview_Quotation'),
    path('squotation/<str:pk>/' , slquotation, name='slist_Quotation'),
    path('quotation/', include('quotation.urls')),
    path('createpurchaseorder/',create_POID,name= 'create_POID'),
    path('createpurchaseorder/<int:pk>/',create_PurchaseOrder, name='create_PurchaseOrder'),
    path('PurchaseOrder/',include('PurchaseOrder.urls')),
]

myproject/quotation/urls.py
from django.urls import path , re_path
from . import views

urlpatterns= [
    path('view_Quotation/', views.view_Quotation , name = 'vieWqcon'),
    path('view_sQuotation/', views.view_sQuotation , name = 'viewqsec'),
    path('quotation/<str:pk>/' , views.lquotation, name='q'),
    # path('update_status/', views.update_status, name='update_status'),
    path('confirm_change/', views.confirm_change, name='confirm_change'),
    path('listQ/' , views.listQ, name='listQ'),
]

myproject/quotation/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import Seller
from decimal import Decimal

# Create your models here.


class quotation(models.Model):
    Quotation_ID = models.AutoField(primary_key=True)
    Quotation_Number = models.CharField(max_length=15, null=True)
    Valid_Date = models.DateField(max_length=6,null=True)
    Creation_Date = models.DateTimeField(auto_now_add=True,null = True)
    status = models.BooleanField(default=False)
    seller_ID = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True)
    

    def __str__(self):
        return str(self.Quotation_ID)

class QuotationProduct(models.Model):
    Product_ID = models.AutoField(primary_key=True)
    name = models.TextField(max_length=20)
    price = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal('0.00'))
    description = models.TextField(max_length= 60)
    proposed_quantity = models.IntegerField(null=False)
    selected_quantity = models.IntegerField(blank=True, null=True)
    Total_Price = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal('0.00'))
    quotation_id = models.ForeignKey(quotation, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.Product_ID)

    

myproject/quotation/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from .models import quotation, QuotationProduct

class CreateQuotationForm(forms.Form):
    quotation_number = forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Quotation Number'}))
    valid_date = forms.DateField(label="Valid Date",
                                 widget=forms.SelectDateWidget(attrs={'class': 'form-control'}))
    product_name = forms.CharField(max_length=50,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Product Name'}))
    product_description = forms.CharField(max_length=100,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Description'}))
    product_price = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput({'class': 'form-control','placeholder': 'Price'}))
    product_quantity =forms.IntegerField(min_value=0,widget=forms.NumberInput({'class': 'form-control','placeholder': 'Quantity'}))
 
class selectedQuantityForm(forms.ModelForm):
    selected_quantity = forms.IntegerField()
    class Meta:
        model = QuotationProduct
        fields =['selected_quantity']

myproject/quotation/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from .forms import CreateQuotationForm, selectedQuantityForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from .models import Seller, quotation, QuotationProduct
from django.contrib.auth.decorators import login_required
from django.urls import reverse

#Seller - Adam
def sview_Quotation(request):
    seller=Seller.objects.get(seller_user=request.user)
    quotation.objects.all().filter(Quotation_Number= None).delete()
    quotation_list = quotation.objects.all().filter(seller_ID=seller)
    status =[]
    for q in quotation_list:
        if q.status == True:
            status.append("Selected")
        else: 
            status.append("Not Selected")
    context ={'quotation_list': quotation_list,
              'status': status}
    return render(request,'app/sellerviewquotation.html',context)

def slquotation(request, pk):
  products = QuotationProduct.objects.all().filter(quotation_id=pk) 
  total = 0
  for p in products:
    total+= p.Total_Price
  q = quotation.objects.get(Quotation_ID=pk)
  seller = Seller.objects.get(seller_user=request.user)

  context = {'products': products,
             'quotation': q,
             'seller': seller,
             'total': total}
  return render(request, 'app/sellerquotation.html',context)


@login_required
def create_quotationID(request):
    current_user = Seller.objects.get(seller_user=request.user)
    thisquotation = quotation(seller_ID=current_user)
    thisquotation.save()
    pk=thisquotation.Quotation_ID
    return redirect(reverse(create_quotation,args=[pk]))

def create_quotation(request,pk):


    quotation_form = CreateQuotationForm(request.POST) 

    if request.method == 'POST':                       
        if quotation_form.is_valid() :
            quotation.objects.filter(Quotation_ID=pk).update(Quotation_Number=quotation_form.cleaned_data['quotation_number'],
                                                            Valid_Date=quotation_form.cleaned_data['valid_date'])

            product= QuotationProduct(name=quotation_form.cleaned_data['product_name'],
                                        description=quotation_form.cleaned_data['product_description'],
                                        price=quotation_form.cleaned_data['product_price'],
                                        proposed_quantity=quotation_form.cleaned_data['product_quantity'],
                                        Total_Price=quotation_form.cleaned_data['product_price'] * quotation_form.cleaned_data['product_quantity'],
                                        quotation_id=quotation.objects.get(Quotation_ID=pk))
            product.save()
    
    products=QuotationProduct.objects.all().filter(quotation_id=pk)
    totalPrice=0

    for product in products:
        totalPrice+=product.Total_Price
    context = {'quotationform':quotation_form,
                'products':products,
                'totalPrice':totalPrice}
    return render(request,'app/create_quotation.html',context)



# Staff -Anas
product_list = QuotationProduct.objects.all()
quotation_list = quotation.objects.all()
quotation_list_selected = quotation.objects.filter(status=True)


def view_Quotation(request):
    status =[]
    for q in quotation_list:
        if q.status == True:
            status.append("Selected")
        else: 
            status.append("Not Selected")
    return render(request,'app/viewqcon.html',{'quotation_list': quotation_list})

def view_sQuotation(request):
    status =[]
    for q in quotation_list_selected:
        if q.status == True:
            status.append("Selected")
        else: 
            status.append("Not Selected")
    return render(request,'app/viewqsec.html', {'quotation_list': quotation_list_selected})

def lquotation(request, pk):
    products = QuotationProduct.objects.all().filter(quotation_id=pk)
    q = quotation.objects.get(Quotation_ID=pk)
    # seller = Seller.objects.get(seller_user=request.user)

    if request.method == 'POST':
        for product in products:
            selected_quantity = request.POST.get('selected_quantity_{}'.format(product.Product_ID))
            product.selected_quantity = selected_quantity
            product.save()
        return HttpResponseRedirect(reverse('menu'))
    context = {'data':products,
                'quotation':q,
                }
    return render(request, 'app/quotation.html',context)

# def update_status(request, pk):
#     # Get the object that you want to update
#     qs = quotation.objects.all().filter(Quotation_ID=pk)
#     if request.method == 'POST':
#         # Update the boolean value
#         qs.status = not qs.status
#         qs.save()
#         # Redirect the user or display a confirmation message
#         return redirect('/success/')
#     return render(request, 'viewqcon.html', {'qs': qs})

# def update_status(request):
#     if request.method == 'POST':
#         task_id = request.POST['Quotation_ID']
#         task = quotation.objects.get(id=task_id)
#         task.status = True
#         task.save()
#         return redirect('vieWqcon')
#     else:
#         return render(request, 'vieWqcon.html')

def confirm_changes(request):
    return render(request, 'app/confirm_change.html')

# def confirm_changes(request):
#     if request.method == 'POST':
#         qs = quotation.objects.get(Quotation_ID=id)
#         qs.status = request.POST.get('change_value')
#         qs.save()
#         return redirect('confirm_change')
#     return render(request, 'viewqcon.html')

def confirm_change(request):
    if request.method == 'POST':
        quotation_id = request.POST.get('quotation_id')
        change_value = request.POST.get('change_value')
        quotation_obj = quotation.objects.get(Quotation_ID=quotation_id)
        quotation_obj.status = change_value
        quotation_obj.save()
        return HttpResponseRedirect(reverse('menu'))
    return render(request, 'app/viewqcon.html')

#Iskanth
def listQ(request):
   
    quotations = quotation.objects.all()
    
    return render(request, 'app/quotationR.html', {'quotations': quotations} )

myproject/quotation/templates/app/confirm_change.html
{% extends "app/layout.html" %}
{% block content %}
<h1>Selected Succcessfully</h1>
{% endblock %}

myproject/quotation/templates/app/create_quotation.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Adam -->
<h1>Create Quotation</h1>

<div>
    <form  method="POST" action ="" id="qform">
        {%csrf_token%}
        <div>
          <label>Quotation Number</label>
          {{ quotationform.quotation_number}}
        </div>
        <div>
          <label>Valid Date</label>
          {{ quotationform.valid_date}}
        </div>
        
        <div class="form-group row">
          <div class="col-md-2">
              <label  class="col-form-label">Product Name</label>
              {{ quotationform.product_name }}
          </div>
          <div class="col-md-2">
              <label  class="col-form-label">Product Description</label>
              {{ quotationform.product_description }}
          </div>
          <div class="col-md-2">
              <label class="col-form-label">Product Price</label>
              {{ quotationform.product_price }}
          </div>
          <div class="col-md-2">
              <label  class="col-form-label">Product Quantity</label>
              {{ quotationform.product_quantity }}
          </div>
          <div class="col-md-2">
            <input type="submit" form="qform" name="submitButton" value="Add Product">
          </div>
      </div>
    </form>
</div>

  
<table class="table table-striped">
    <tr>
      <th>name</th>
      <th>description</th>
      <th>price</th>
      <th>quantity</th>
      <th>Total price</th>
    </tr>

    {{TotalPrice}}
    {% for product in products %}
    <tr>
      <td>{{product.name}}</td>
      <td>{{product.description}}</td>
      <td>{{product.price}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td>{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>{{totalPrice}}</td>
    </tr>
  </table> 
  
  <div>
    <a href="{% url 'menu' %}">
      <button>Submit</button>
    </a>
   
  </div>

{% endblock %}

myproject/quotation/templates/app/quotation.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Anas -->
<h1>Quotation #{{quotation.Quotation_Number}}</h1>
<h3>Quotation Valid Date: {{quotation.Valid_Date}}</h3>
<h3>Seller Name: {{quotation.seller_ID.seller_name}}</h3>
<h3>Seller Address: {{quotation.seller_ID.seller_address}}</h3>

<form method="post" action="">
  {% csrf_token %}
  <table class="table table-striped">
    <tr>
      <th>Product ID</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>proposed quantity</th>
      <th>selected quantity</th>
      <th>Total price</th>
    </tr>
    {% for product in data %}
    <tr>
      <td>{{product.Product_ID}}</td>
      <td>{{product.name}}</td>
      <td style="text-align: left;">{{product.price}}</td>
      <td>{{product.description}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td>
        <input type="number" name="selected_quantity_{{ product.Product_ID }}" value="{{ product.selected_quantity }}">
      </td>
      <td style="text-align: left;">{{product.Total_Price}}</td>

    </tr>
    {% endfor %}

  </table>
  <input type="submit" value="Save All">
</form>
{% endblock %}

myproject/quotation/templates/app/quotationR.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Iskanth -->
<h1>Quotation Report</h1>
{% for quotation in quotations %}
<h2>Quotation #{{ quotation.Quotation_Number }}</h2>
<h3>Quotation Valid Date: {{quotation.Valid_Date}}</h3>
<h3>Seller Name: {{quotation.seller_ID.seller_name}}</h3>
<h3>Seller Address: {{quotation.seller_ID.seller_address}}</h3>
<table class="table table-striped">
    <tr>
        <th>Product ID</th>
        <th>name</th>
        <th>price</th>
        <th>description</th>
        <th>proposed quantity</th>
        <th>selected quantity</th>
        <th>Total price</th>
    </tr>
    {% for product in quotation.quotationproduct_set.all %}
    <tr>
        <td>{{product.Product_ID}}</td>
        <td>{{product.name}}</td>
        <td style="text-align: left;">{{product.price}}</td>
        <td>{{product.description}}</td>
        <td>{{product.proposed_quantity}}</td>
        <td>{{product.selected_quantity}}</td>
        <td style="text-align: left;">{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
</table>

</ul>
{% endfor %}
{% endblock %}

myproject/quotation/templates/app/selectedQ.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Emad -->
<h1>{{products.quotation_id.all}}</h1>

<table class="table table-striped">
    <tr>
      <th>Product ID</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>validity date</th>
      <th>quantity</th>
      <th>Total price</th>
    </tr>
    {% for product in products %}
    <tr>
      <td>{{product.Product_ID}}</td>
      <td>{{product.name}}</td>
      <td>{{product.price}}</td>
      <td>{{product.description}}</td>
      <td>{{product.Valid_Date}}</td>
      <td>{{product.quantity}}</td>
      <td>{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
  </table> 
{% endblock %}

myproject/quotation/templates/app/selectquotation.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Anas -->
<h1>Quotation #{{quotation.Quotation_Number}}</h1>
<h3>Quotation Valid Date: {{quotation.Valid_Date}}</h3>
<h3>Seller Name: {{seller.seller_name}}</h3>
<h3>Seller Address: {{seller.seller_address}}</h3>

<form method="post" action="">
  {% csrf_token %}
  <table class="table table-striped">
    <tr>
      <th>Product ID</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>proposed quantity</th>
      <th>selected quantity</th>
      <th>Total price</th>
    </tr>
    {% for product in data %}
    <tr>
      <td >{{product.Product_ID}}</td>
      <td>{{product.name}}</td>
      <td style="text-align: left;">{{product.price}}</td>
      <td>{{product.description}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td>
        <input type="number" name="selected_quantity_{{ product.Product_ID }}" value="{{ product.selected_quantity }}">
      </td>
      <td style="text-align: left;">{{product.Total_Price}}</td>
      
    </tr>
    {% endfor %}
   
  </table> 
  <input type="submit" value="Save All">
</form>
{% endblock %}

myproject/quotation/templates/app/sellerquotation.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Adam -->
<h1>Quotation #{{quotation.Quotation_Number}}</h1>
<h3>Quotation Valid Date: {{quotation.Valid_Date}}</h3>
<h3>Seller Name: {{seller.seller_name}}</h3>
<h3>Seller Address: {{seller.seller_address}}</h3>

<table class="table table-striped">
    <tr>
      <th>Product ID</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>quantity</th>
      <th>Total price</th>
    </tr>
    {% for product in products %}
    <tr>
      <td >{{product.Product_ID}}</td>
      <td>{{product.name}}</td>
      <td style="text-align: left;">{{product.price}}</td>
      <td>{{product.description}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td style="text-align: left;">{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td style="text-align: left;">RM{{total}}</td>
    </tr>
  </table> 
{% endblock %}

myproject/quotation/templates/app/sellerviewquotation.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Adam -->
<h1>View Quotations</h1>
<table class="table table-striped">
  <tr>
    <td>Quotation ID</td>
    <td>Quotation Number</td>
    <td>Creation Date</td>
    <td>Status</td>
    <td></td>
  </tr>
  {% for quotation in quotation_list %}
  <tr>
    <td>{{ quotation.Quotation_ID }}</td>
    <td>{{ quotation.Quotation_Number }}</td>
    <td>{{ quotation.Creation_Date }}</td>
    <td>{% if quotation.status %}Selected{% else %}Not Selected{% endif %}</td>
    <td><a class="btn btn-primary" href="{% url 'slist_Quotation' quotation.Quotation_ID %}">View</a></td>
    
  </tr>
  {% endfor %}
</table>
{% endblock %}

myproject/quotation/templates/app/viewqcon.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Anas -->
<h1>View Quotations</h1>
<table class="table table-striped">
  <tr>
    <td>Quotation ID</td>
    <td>Quotation Date</td>
    <td>Status</td>
    <td></td>
  </tr>
  {% for quotation in quotation_list %}
  <tr>
    <td>{{ quotation.Quotation_ID }}</td>
    <td>{{ quotation.Creation_Date }}</td>
    <td>{% if quotation.status %}Selected{% else %}Not Selected{% endif %}</td>
    <td><a class="btn btn-primary" href="{% url 'q' quotation.Quotation_ID %}">View</a></td>
    <td>
      <form action="{% url 'confirm_change' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="quotation_id" value="{{ quotation.Quotation_ID }}">
        <input type="hidden" name="change_value" value="True">
        <button type="submit">Select</button>
      </form>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

myproject/quotation/templates/app/viewqsec.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Emad -->
<h1>View Selected Quotations</h1>
<table class="table table-striped">
  <tr>
    <td>Quotation ID</td>
    <td>Quotation Date</td>
    <td>Status</td>
    <td></td>
  </tr>
  {% for quotation in quotation_list %}
  <tr>
    <td>{{ quotation.Quotation_ID }}</td>
    <td>{{ quotation.Creation_Date }}</td>
    <td>{% if quotation.status %}Selected{% else %}Not Selected{% endif %}</td>
    <td><a class="btn btn-primary" href="{% url 'q' quotation.Quotation_ID %}">View</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}