myproject/PurchaseOrder/urls.py
from django.urls import path , re_path
from . import views

urlpatterns = [

    path('listPOs/', views.listPOs, name='listPOs'),
    path('view_PurchaseOrders/', views.view_PurchaseOrders , name = 'view_PurchaseOrders'),
    path('financeOrders/<str:pk>/',views.financeOrders, name='financeOrders')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app import views, forms
import django.contrib.auth.views
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from app.views import register_seller
from quotation.views import create_quotation,create_quotationID,sview_Quotation,slquotation
from PurchaseOrder.views import create_POID, create_PurchaseOrder
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^contact$', views.contact, name='contact'),
    re_path(r'^about$', views.about, name='about'),
    re_path(r'^login/$',
        LoginView.as_view(template_name = 'app/login.html'),
        name='login'),
    re_path(r'^logout$',
        LogoutView.as_view(template_name = 'app/index.html'),
        name='logout'),
    re_path(r'^menu$', views.menu, name='menu'),
    path('register/', register_seller, name='register'),
    path('createquotation/',create_quotationID, name='create_quotationID'),
    path('createquotation/<int:pk>/',create_quotation, name='create_quotation'),
    path('sview_Quotation/', sview_Quotation , name = 'sview_Quotation'),
    path('squotation/<str:pk>/' , slquotation, name='slist_Quotation'),
    path('quotation/', include('quotation.urls')),
    path('createpurchaseorder/',create_POID,name= 'create_POID'),
    path('createpurchaseorder/<int:pk>/',create_PurchaseOrder, name='create_PurchaseOrder'),
    path('PurchaseOrder/',include('PurchaseOrder.urls')),
]

myproject/PurchaseOrder/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import Finance 
from decimal import Decimal

# Create your models here.

#Iskanth and Emad
class purchaseOrder(models.Model):
    PO_ID = models.AutoField(primary_key=True)
    Purchaseorder_Number = models.CharField(max_length=15, null=True)
    Valid_Date = models.DateField(max_length=6,null=True)
    Creation_Date = models.DateTimeField(auto_now_add=True,null = True)
    status = models.BooleanField(default=False)
    finance_ID = models.ForeignKey(Finance, on_delete=models.CASCADE, null=True)
    Seller_Name = models.TextField(max_length= 30)
    Seller_Address = models.TextField(max_length= 100)
    Quotation_Number = models.CharField(max_length=15, null=True)
    

    def __str__(self):
        return str(self.PO_ID)

class PurchaseOrderProduct(models.Model):
    Product_ID = models.AutoField(primary_key=True)
    name = models.TextField(max_length=20)
    price = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal('0.00'))
    description = models.TextField(max_length= 60)
    proposed_quantity = models.IntegerField(null=False)
    selected_quantity = models.IntegerField(blank=True, null=True)
    Total_Price = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal('0.00'))
    purchaseorder_id = models.ForeignKey(purchaseOrder, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.Product_ID)

myproject/PurchaseOrder/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from PurchaseOrder.models import purchaseOrder, PurchaseOrderProduct 

class CreatePurchaseOrderForm(forms.Form):
    PurchaseOrder_number = forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Purchase Order Number'}))
    quotation_Number = forms.CharField(max_length=20,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Quotation Reference Number'}))
            
    valid_date = forms.DateField(label="Valid Date",
                                 widget=forms.SelectDateWidget(attrs={'class': 'form-control'}))
    sellername = forms.CharField(max_length=100,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Seller Name'}))

    selleraddress = forms.CharField(max_length=255,
                                widget=forms.TextInput({
                                    'class': 'form-control',
                                    'placeholder': 'SellerAddress'}))
    product_name = forms.CharField(max_length=50,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Product Name'}))
    product_description = forms.CharField(max_length=100,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Description'}))
    product_price = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.TextInput({'class': 'form-control','placeholder': 'Price'}))
    product_quantity =forms.IntegerField(min_value=0,widget=forms.NumberInput({'class': 'form-control','placeholder': 'Quantity'}))
 
class selectedQuantityForm(forms.ModelForm):
    selected_quantity = forms.IntegerField()
    class Meta:
        model = PurchaseOrderProduct
        fields =['selected_quantity']

myproject/PurchaseOrder/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from quotation.forms import CreateQuotationForm, selectedQuantityForm
from PurchaseOrder.forms import CreatePurchaseOrderForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from app.models import Seller, Finance
from quotation.models import quotation, QuotationProduct
from PurchaseOrder.models import purchaseOrder, PurchaseOrderProduct
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

#Iskanth and Emad
@login_required
def create_POID(request):
    current_user = Finance.objects.get(Finance_user=request.user)
    thispurchaseorder = purchaseOrder(finance_ID=current_user)
    thispurchaseorder.save()
    pk=thispurchaseorder.PO_ID
    return redirect(reverse(create_PurchaseOrder,args=[pk]))

#Emad
def create_PurchaseOrder(request,pk):


    purchaseorder_form = CreatePurchaseOrderForm(request.POST) 

    if request.method == 'POST':                       
        if purchaseorder_form.is_valid() :
            purchaseOrder.objects.filter(PO_ID=pk).update(Purchaseorder_Number=purchaseorder_form.cleaned_data['PurchaseOrder_number'],
                                                          Quotation_Number=purchaseorder_form.cleaned_data['quotation_Number'],
                                                            Valid_Date=purchaseorder_form.cleaned_data['valid_date'],
                                                            Seller_Name=purchaseorder_form.cleaned_data['sellername'],
                                                            Seller_Address=purchaseorder_form.cleaned_data['selleraddress'])

            product= PurchaseOrderProduct(name=purchaseorder_form.cleaned_data['product_name'],
                                        description=purchaseorder_form.cleaned_data['product_description'],
                                        price=purchaseorder_form.cleaned_data['product_price'],
                                        proposed_quantity=purchaseorder_form.cleaned_data['product_quantity'],
                                        Total_Price=purchaseorder_form.cleaned_data['product_price'] * purchaseorder_form.cleaned_data['product_quantity'],
                                        purchaseorder_id=purchaseOrder.objects.get(PO_ID=pk))
            product.save()
    
    products=PurchaseOrderProduct.objects.all().filter(purchaseorder_id=pk)
    totalPrice=0

    for product in products:
        totalPrice+=product.Total_Price
    context = {'purchaseorderform':purchaseorder_form,
                'products':products,
                'totalPrice':totalPrice}
    return render(request,'app/create_PO.html',context)

#Emad
def view_PurchaseOrders(request):
    finance=Finance.objects.get(Finance_user=request.user)
    purchaseOrder.objects.all().filter(Purchaseorder_Number= None).delete()
    purchaseorder_list = purchaseOrder.objects.all().filter(finance_ID=finance)
    context ={'purchaseorder_list': purchaseorder_list,}
    return render(request,'app/View_PO.html',context)

#Emad
def financeOrders(request, pk):
  products = PurchaseOrderProduct.objects.all().filter(purchaseorder_id=pk) 
  total = 0
  for p in products:
    total+= p.Total_Price
  p = purchaseOrder.objects.get(PO_ID=pk)
  finance = Finance.objects.get(Finance_user=request.user)

  context = {'products': products,
             'PurchaseOrder': p,
             'finance': finance,
             'total': total}
  return render(request, 'app/View_POdetails.html',context)


#Iskanth
def listPOs(request):

    purchasorders = purchaseOrder.objects.all()


    return render(request, 'app/View_POReport.html', {'purchaseorders': purchasorders} )

myproject/PurchaseOrder/templates/app/Create_PO.html
{% extends "app/layout.html" %}
{% block content %}

<!-- Emad -->

<h1>Generate Purchase Order</h1>

<div>
    <form  method="POST" action ="" id="qform">
        {%csrf_token%}
        <div>
          <label>Purchase Order Number</label>
          {{ purchaseorderform.PurchaseOrder_number}}
        </div>
        <div>
          <label>Referenced Quotation Number</label>
          {{ purchaseorderform.quotation_Number}}
        </div>
        <div>
          <label>Valid Date</label>
          {{ purchaseorderform.valid_date}}
        </div>

        <div>
          <label>Seller Name</label>
          {{ purchaseorderform.sellername}}
        </div>

        <div>
          <label>Seller Address</label>
          {{ purchaseorderform.selleraddress}}
        </div>
        
        <div class="form-group row">
          <div class="col-md-2">
              <label  class="col-form-label">Product Name</label>
              {{ purchaseorderform.product_name }}
          </div>
          <div class="col-md-2">
              <label  class="col-form-label">Product Description</label>
              {{ purchaseorderform.product_description }}
          </div>
          <div class="col-md-2">
              <label class="col-form-label">Product Price</label>
              {{ purchaseorderform.product_price }}
          </div>
          <div class="col-md-2">
              <label  class="col-form-label">Product Quantity</label>
              {{ purchaseorderform.product_quantity }}
          </div>
          <div class="col-md-2">
            <input type="submit" form="qform" name="submitButton" value="Add Product">
          </div>
      </div>
    </form>
</div>

  
<table class="table table-striped">
    <tr>
      <th>name</th>
      <th>description</th>
      <th>price</th>
      <th>quantity</th>
      <th>Total price</th>
    </tr>

    {{TotalPrice}}
    {% for product in products %}
    <tr>
      <td>{{product.name}}</td>
      <td>{{product.description}}</td>
      <td>{{product.price}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td>{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>{{totalPrice}}</td>
    </tr>
  </table> 
  
  <div>
    <a href="{% url 'menu' %}">
      <button>Submit</button>
    </a>
   
  </div>

{% endblock %}

myproject/PurchaseOrder/templates/app/View_PO.html
{% extends "app/layout.html" %}
{% block content %}

<!-- Emad -->
<h1>View PurchaseOrders</h1>
<table class="table table-striped">
  <tr>
    <td>PurchaseOrder ID</td>
    <td>PurchaseOrder Number</td>
    <td>Referenced Quotation Number</td>
    <td>Creation Date</td>
    <td></td>
  </tr>
  {% for purchaseorder in purchaseorder_list %}
  <tr>
    <td>{{ purchaseorder.PO_ID }}</td>
    <td>{{ purchaseorder.Purchaseorder_Number}}</td>
    <td>{{ purchaseorder.Quotation_Number}}</td>
    <td>{{ purchaseorder.Creation_Date }}</td>
    <td><a class="btn btn-primary" href="{% url 'financeOrders' purchaseorder.PO_ID %}">View</a></td>
    
  </tr>
  {% endfor %}
</table>
{% endblock %}

myproject/PurchaseOrder/templates/app/View_POReport.html
{% extends "app/layout.html" %}
{% block content %}

<!-- Iskanth -->
<h1>Purchase Order Report</h1>
{% for purchaseorder in purchaseorders %}
<h2>Purchase Order #{{ purchaseorder.Purchaseorder_Number }}</h2>
<h2>Referenced Quotation #{{ purchaseorder.Quotation_Number }}</h2>
<h3>Purchase Order Valid Date: {{purchaseorder.Valid_Date}}</h3>
<h3>Seller Name: {{purchaseorder.Seller_Name}}</h3>
<h3>Seller Address: {{purchaseorder.Seller_Address}}</h3>
<table class="table table-striped">
    <tr>
        <th>Product ID</th>
        <th>name</th>
        <th>price</th>
        <th>description</th>
        <th>proposed quantity</th>
        <th>selected quantity</th>
        <th>Total price</th>
    </tr>
    {% for product in purchaseorder.purchaseorderproduct_set.all %}
    <tr>
        <td>{{product.Product_ID}}</td>
        <td>{{product.name}}</td>
        <td style="text-align: left;">{{product.price}}</td>
        <td>{{product.description}}</td>
        <td>{{product.proposed_quantity}}</td>
        <td>{{product.selected_quantity}}</td>
        <td style="text-align: left;">{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
</table>

</ul>
{% endfor %}
{% endblock %}

myproject/PurchaseOrder/templates/app/View_POdetails.html
{% extends "app/layout.html" %}
{% block content %}
<!-- Iskanth -->
<h1>PurchaseOrder #{{PurchaseOrder.Purchaseorder_Number}}</h1>
<h1>Referenced Quotation #{{PurchaseOrder.Quotation_Number}}</h1>
<h3>PurchaseOrder Valid Date: {{PurchaseOrder.Valid_Date}}</h3>
<h3>Seller Name: {{PurchaseOrder.Seller_Name}}</h3>
<h3>Seller Address: {{PurchaseOrder.Seller_Address}}</h3>


<table class="table table-striped">
    <tr>
      <th>Product ID</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>quantity</th>
      <th>Total price</th>
    </tr>
    {% for product in products %}
    <tr>
      <td >{{product.Product_ID}}</td>
      <td>{{product.name}}</td>
      <td style="text-align: left;">{{product.price}}</td>
      <td>{{product.description}}</td>
      <td>{{product.proposed_quantity}}</td>
      <td style="text-align: left;">{{product.Total_Price}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td style="text-align: left;">RM{{total}}</td>
    </tr>
  </table> 
{% endblock %}